redirectsOrigin = "config"
plugins = []
headers = []

[dev]
command = "npx serve ."
port = 3000.0
publish = "."

[functions]

[functions."*"]

[build]
publish = "D:\\proyect\\calc inversiones"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Static site, no build needed'"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]